services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dinosaur_db
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mariadb-admin", "-h", "localhost", "-proot", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .

    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/dinosaur_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
