spring:
  application:
    name: FroneusChallenge
  datasource:
    url: jdbc:mariadb://localhost:3306/dinosaur_db
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: true